# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
  # When we'll update to a version where https://github.com/RasaHQ/rasa/issues/6741 is solved,
  # we'll change it back to the ConveRT tokenizer and featurizer
  - name: WhitespaceTokenizer
  # - name: ConveRTTokenizer
  # - name: ConveRTFeaturizer
  #   case_sensitive: false
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
    case_sensitive: false
  - name: CountVectorsFeaturizer
    case_sensitive: false
  - name: CountVectorsFeaturizer
    case_sensitive: false
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
