runs:
  using: "composite"
  steps:
    - name: Set up Python 3.6.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.8
    - name: Installing poetry
      run: |
        export $( \
            PYTHONFAULTHANDLER=TRUE \
            PYTHONUNBUFFERED=TRUE \
            PIP_DISABLE_PIP_VERSION_CHECK=on \
            PIP_NO_CACHE_DIR=off \
        )
        pip install --upgrade pip \
        && pip install "poetry==1.0.5"
